export const ACTIONS = {
  ARTICLES: {
    FETCH: "ARTICLES_FT",
    FAILURE_FETCH: "ARTICLES_FL",
    GET_ALL_SC: "ARTICLES_GET_ALL_SC",
    GET_ONE_SC: "ARTICLES_GET_ONE_SC",
    UPDATE_SC : "ARTICLES_UPDATE_SC",
    CREATE_SC : "ARTICLES_CREATE_SC",
    SELECTED  : "ARTICLES_CREATE_SELECTED",
  }
};